OSBI_SUPPORT ?= y
SPL_SUPPORT ?= y
V5V2_SUPPORT ?= y
UBOOT_VERSION = 1ebd659cf020843fd8e8ef90d85a66941cbab6ec
linux_defconfig := $(confdir)/defconfig
# linux_dtb := $(riscv_dtbdir)/starfive/jh7110-starfive-visionfive-2-va.dtb
linux_dtb := $(riscv_dtbdir)/starfive/jh7110-starfive-visionfive-2-v1.2a.dtb
buildroot_initramfs_config := $(confdir)/$(DEVKIT)/buildroot_initramfs_config
its_file := $(confdir)/32-bit-fit-image.its
tftp_boot_scr := vision5v2-boot.scr